package com.v6ak.zbdb.checkpoint

import com.v6ak.zbdb.checkpoint.Templates.tags.main
import org.scalajs.dom.Node
import org.scalajs.dom.raw.HTMLInputElement
import scalatags.JsDom.all._

abstract class TableFormPage extends AutogeneratedPage {

  def pageTitle: String

  def formItems: Seq[Frag]

  def primaryField: HTMLInputElement

  override final def create(): Node = Seq(
    Templates.dialogHeader(pageTitle, "#table"),
    main(role:="main", cls:="mdc-toolbar-fixed-adjust")(
      formItems
    )
  ).render

  override def onShow(): Unit ={
    primaryField.focus()
  }

}
