package com.v6ak.zbdb.checkpoint

import scalatags.JsDom.all._
import Templates.tags._
import org.scalajs.dom.Node

class DeparturePage() extends AutogeneratedPage{
  override def create(): Node = Seq(
    Templates.dialogHeader("Odchod ze stanoviště", "#table"),
    main(role:="main", cls:="mdc-toolbar-fixed-adjust")(
      section(
        div(cls:="mdc-text-field")(
          input(tpe:="time", cls:="mdc-text-field__input", id:="departure-time"),
          "(prázdné políčko se vyplní po odeslání)",
          label(cls:="mdc-floating-label", `for`:="departure-time")("Čas odchodu (nepovinné)"),
          div(cls:="mdc-line-ripple"),
        )
      ),
      section(cls:="participant-list-section")
    )
  ).render
}
